version: '3.2'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: scraper
      POSTGRES_USER: notadmin
      POSTGRES_PASSWORD: secure123
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
